spring:
  docker:
    compose:
      enabled: true
      file: docker-compose.yml
  jpa:
    hibernate:
      ddl-auto:
        none
  datasource:
    url:
      jdbc:mysql://localhost:3307/mydb
    username:
      bug_user
    password:
      "{cipher}9fbdeeeb711c7dea6b99040b1cb7c6ef942ff7eb399316190f1141e18ed94658"
    driver-class-name:
      com.mysql.cj.jdbc.Driver
management:
  endpoint:
    env:
      show-values: always