spring:
  jpa:
    hibernate:
      ddl-auto:
        none
  datasource:
    url:
      jdbc:mysql://localhost:3307/mydb
    username:
      bug_user
    password:
      "{cipher}3504f4d7fb338692fbe152bed2f5a746f7f97688cb2aa078cfb8aa85ae252c30"
    driver-class-name:
      com.mysql.cj.jdbc.Driver
management:
  endpoint:
    env:
      show-values: always
    configprops:
      show-values: always